baseURL = 'https://abazure.github.io/'
title = 'Abazure.dev'
theme = 'chicago7'

# Situs berbahasa Indonesia
defaultContentLanguage = 'id'

[languages.id]
  locale = 'id-ID'
  label = 'Indonesia'
  weight = 1

pagination.pagerSize = 10

[permalinks]
  posts = '/posts/:slug/'

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = 'bw'

# ---------------------------------------------------------
# MENU NAVIGASI
# ---------------------------------------------------------
[menu]
  [[menu.header]]
    name = 'Home'
    url = '/'
    weight = 10

  [[menu.header]]
    name = 'Posts'
    url = 'posts'
    weight = 20

  [[menu.header]]
    name = 'Projects'
    url = 'projects'
    weight = 30

  [[menu.header]]
    name = 'About'
    url = 'about'
    weight = 40

# ---------------------------------------------------------
# PARAMETER SITUS
# ---------------------------------------------------------
[params]
  author = 'Roni Ragil Iman Khoirul'
  subtitle = 'Sederet catatan, ide, dan refleksi di tiap langkah kaki.'
  keywords = 'linux, sysadmin, catatan, teknologi'
  logo = 'logo.png'
  favicon = 'favicon/favicon.ico'

[params.social]
  github = 'https://github.com/abazure'
  linkedin = 'https://www.linkedin.com/in/roni-ragil-iman-khoirul'
  feed = '/index.xml'

[outputs]
  home = ['HTML', 'RSS']
